/*
 * Copyright 2015 Coursera Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.coursera.courier.android;

import org.apache.commons.lang3.StringUtils;

/**
 * Cleans up Java source code generated by a string template engine.
 *
 * Ideally, we would use a grammar aware formatter for Java (I found Jalopy, but it old,
 * unmaintained, and depends on old versions of libraries like log4j that are incompatible with
 * other dependencies we need). Until we find something good, we'll use this.
 *
 * What it does:
 * - To sanitize whitespace, collapses consecutive empty lines to a single empty line.
 * - To keep javadoc and annotations directly above class and field definitions, collapses any
 *   empty lines after a line starting with '*' or '@'.
 * - Auto-indents '{', '}' delimited code blocks correctly so long as '{' is always the last and '}'
 *   is always the first non-whitespace char on a line.
 * - Removes any tailing whitespace from the ends of lines.
 * - Treats all lines starting with a '*' as a continuation of a Javadoc comment and indents them
 *   one additional space.
 *
 * This routine only modifies whitespace that is either on an empty line or that precedes or trails
 * the code on any particular line. The code from the fist non-whitespace char to the last on
 * each line of code is left unmodified.
 *
 */
public class PoorMansJavaSourceFormatter {
  public static String format(String code) {
    String lines[] = code.split("\\r?\\n");
    StringBuilder result = new StringBuilder();

    int indentLevel = 0;
    boolean isPreviousLineEmpty = true;
    boolean isPreviousLinePreamble = false;

    for (String line: lines) {
      line = line.trim();

      boolean isEmpty = (line.length() == 0);
      if (isEmpty && (isPreviousLineEmpty || isPreviousLinePreamble)) continue; // skip it

      if (line.startsWith("}")) {
        indentLevel--;
      }
      result.append(StringUtils.repeat("  ", indentLevel));
      if (line.startsWith("*")) { // align javadoc
        result.append(" ");
      }
      result.append(line);
      result.append('\n');

      if (line.endsWith("{")) {
        indentLevel++;
      }

      isPreviousLinePreamble = (line.startsWith("@") || line.startsWith("*"));
      isPreviousLineEmpty = isEmpty;
    }
    return result.toString();
  }
}
