#!/bin/bash

set -x
set -e

# Publish to Maven
sbt fullpublish-mavenlocal # publish courier to maven local so that the gradle build for gradle-plugin can depend on it
sbt fullpublish-signed
(cd gradle-plugin; gradle uploadArchives)
if hash mvn 2>/dev/null; then
    (cd maven-plugin; mvn deploy -Prelease)
else
    echo "mvn not install, skipping publish for maven-plugin"
fi
